import type { ComponentProps } from 'react';
import { MainLayout } from '../../components/MainLayout';
import { MobileLayout } from '../../components/MobileLayout';
import type {
  MainLayoutFactoryInput,
  MobileLayoutFactoryInput,
} from '../contract/appShellScreenContract';

export const createMobileLayoutProps = (
  input: MobileLayoutFactoryInput
): ComponentProps<typeof MobileLayout> => ({
  title: input.title,
  projects: input.projects,
  selectedProjectId: input.selectedProjectId,
  onProjectSelect: input.onProjectSelect,
  onCreateProject: input.onCreateProject,
  books: input.books,
  citations: input.citations,
  isHomeView: input.isHomeView,
  selectedBookId: input.selectedBookId,
  onHomeSelect: input.onHomeSelect,
  onBookSelect: input.onBookSelect,
  treeData: input.treeData,
  onTreeItemClick: input.onTreeItemClick,
  authorFolderLoading: input.authorFolderLoading,
  authorFolderLoadError: input.authorFolderLoadError,
  onRetryAuthorFolders: input.onRetryAuthorFolders,
  onCreateAuthorFolder: input.onCreateAuthorFolder,
  onRenameAuthorFolder: input.onRenameAuthorFolder,
  onDeleteAuthorFolder: input.onDeleteAuthorFolder,
  onMoveAuthorToFolder: input.onMoveAuthorToFolder,
  onRemoveAuthorFromFolder: input.onRemoveAuthorFromFolder,
  onRenameAuthor: input.onRenameAuthor,
  onDeleteAuthor: input.onDeleteAuthor,
  onPreviewAuthorDelete: input.onPreviewAuthorDelete,
  username: input.username,
  avatarUrl: input.avatarUrl,
  onSignOut: input.onSignOut,
  onSearch: input.onSearch,
  searchTerm: input.searchTerm,
  selectedFilter: input.selectedFilter,
  onOpenSettings: input.onOpenSettings,
  showBookMemoAction: input.showBookMemoAction,
  onOpenBookMemo: input.onOpenBookMemo,
});

export const createMainLayoutProps = (
  input: MainLayoutFactoryInput
): ComponentProps<typeof MainLayout> => ({
  onCloseInlinePassageNotes: input.onCloseInlinePassageNotes,
  onRightPanelOpenChange: input.onRightPanelOpenChange,
  hasInlinePassageNotes: input.hasInlinePassageNotes,
  homePanelOpen: input.homePanelOpen,
  onHomePanelOpenChange: input.onHomePanelOpenChange,
  leftPanel: input.leftPanel,
  rightPanel: input.rightPanel,
  rightPanelOpen: input.rightPanelOpen,
  projects: input.projects,
  onProjectSelect: input.onProjectSelect,
  selectedProjectId: input.selectedProjectId,
  onDropCitationToProject: input.onDropCitationToProject,
  onCreateProject: input.onCreateProject,
  onRenameProject: input.onRenameProject,
  onDeleteProject: input.onDeleteProject,
  onRenameAuthor: input.onRenameAuthor,
  onRenameBook: input.onRenameBook,
  books: input.books,
  citations: input.citations,
  isHomeView: input.isHomeView,
  selectedBookId: input.selectedBookId,
  onHomeSelect: input.onHomeSelect,
  onBookSelect: input.onBookSelect,
  onReorderProjects: input.onReorderProjects,
  treeData: input.treeData,
  onTreeItemClick: input.onTreeItemClick,
  authorFolderLoading: input.authorFolderLoading,
  authorFolderLoadError: input.authorFolderLoadError,
  onRetryAuthorFolders: input.onRetryAuthorFolders,
  onCreateAuthorFolder: input.onCreateAuthorFolder,
  onRenameAuthorFolder: input.onRenameAuthorFolder,
  onDeleteAuthorFolder: input.onDeleteAuthorFolder,
  onMoveAuthorToFolder: input.onMoveAuthorToFolder,
  onRemoveAuthorFromFolder: input.onRemoveAuthorFromFolder,
  onDeleteAuthor: input.onDeleteAuthor,
  onPreviewAuthorDelete: input.onPreviewAuthorDelete,
  avatarUrl: input.avatarUrl,
  onSearch: input.onSearch,
  searchTerm: input.searchTerm,
  selectedFilter: input.selectedFilter,
  onReorderBookAt: input.onReorderBookAt,
  onReorderAuthorAt: input.onReorderAuthorAt,
  libraryOrderSaving: input.libraryOrderSaving,
  onOpenSettings: input.onOpenSettings,
});
