import type { ComponentProps } from 'react';
import { ArchiveScreen } from '../../features/archive/ui/ArchiveScreen';
import type { ArchiveScreenFactoryInput } from '../contract/appShellScreenContract';

export const createArchiveScreenProps = (
  input: ArchiveScreenFactoryInput
): ComponentProps<typeof ArchiveScreen> => ({
  isMobileApp: input.isMobileApp,
  title: input.title,
  showEditor: !input.searchTerm && !input.selectedProjectId,
  username: input.username,
  editorPrefill: input.editorPrefill,
  isBookView: input.isBookView,
  onBackToAuthor: input.onBackToAuthor,
  authorName: input.authorName,
  sortField: input.sortField,
  dateDirection: input.dateDirection,
  pageDirection: input.pageDirection,
  onAddCitation: input.onAddCitation,
  onRetryCitationSave: input.onRetryCitationSave,
  onDateSortClick: input.onDateSortClick,
  onPageSortClick: input.onPageSortClick,
  projects: input.projects,
  citations: input.citations,
  allCitations: input.allCitations,
  chapterBlocks: input.selectedBookId ? input.chapterBlocksByBook[input.selectedBookId] || [] : [],
  loading: input.dataLoading,
  loadError: input.loadError,
  onRetryLoad: input.onRetryLoad,
  searchTerm: input.searchTerm,
  selectedIds: input.selectedIds,
  selectedFilter: input.selectedFilter,
  isCopying: input.isCopying,
  onSelectAll: input.onSelectAll,
  onCopy: input.onCopy,
  onDeleteRequest: input.onBatchDeleteRequest,
  onCancelSelection: input.onCancelSelection,
  onAddToProject: input.onAddToProject,
  onCreateAndAddToProject: input.onCreateAndAddToProject,
  onCreateChapterBlock: input.onCreateChapterBlock,
  onDeleteChapterBlock: input.onDeleteChapterBlock,
  chapterActionsDisabled: input.chapterActionsDisabled,
  onToggleSelect: input.onToggleSelect,
  onAddNote: input.onAddNote,
  onUpdateNote: input.onUpdateNote,
  onDeleteNote: input.onDeleteNote,
  onDeleteCitation: input.onDeleteCitation,
  onUpdateCitation: input.onUpdateCitation,
  passageNoteCitationId: input.passageNoteCitationId,
  onPassageNoteCitationChange: input.onPassageNoteCitationChange,
});
